export const SignUpActionTypes = ({
    CHANGE_NAME_INPUT: 'CHANGE_NAME_INPUT',
    CHANGE_SIGNUP_EMAIL_INPUT: 'CHANGE_SIGNUP_EMAIL_INPUT',
    CHANGE_SIGNUP_PASSWORD_INPUT: 'CHANGE_SIGNUP_PASSWORD_INPUT',
    CHANGE_CONFIRM_PASSWORD_INPUT: 'CHANGE_CONFIRM_PASSWORD_INPUT'
})